name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: |
          docker-compose -f docker-compose.yml build

      - name: Run tests (optional)
        run: |
          docker-compose -f docker-compose.yml run --rm app npm test  

      - name: Push Docker image to Docker Hub (optional)
        if: github.ref == 'refs/heads/main'
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker-compose -f docker-compose.yml push

      - name: Deploy to Server (optional)
        if: github.ref == 'refs/heads/main'
        run: |
          ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "cd /path/to/your/app && git pull && docker-compose up -d"
