name: Backup Repository
# Coder Kaan Oz

on:
  schedule:
    - cron: '0 * * * *'  # EDIT: Runs every night at 12:00 AM GMT
  workflow_dispatch:  # Allows manual execution

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all branches
          ref: feature-branch  # EDIT: Fetch only 'feature-branch'
          token: ${{ secrets.PAT }}  # Requires PAT ***

      - name: Set up Git
        run: |
          echo "Setting up Git configuration"
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Create backup branch
        id: create_branch
        run: |
          echo "Creating backup branch"
          TIMESTAMP=$(TZ="GMT" date +"%Y-%m-%d-%H-%M")  # EDIT: Set timezone to GMT
          BRANCH_NAME="backup-$TIMESTAMP"
          echo "Branch name: $BRANCH_NAME"
          git checkout -b $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Add backup remote
        run: |
          echo "Adding remote backup repository"
          git remote add backup https://${{ secrets.PAT }}@github.com/i-ayo/backupRepo  # EDIT: Set your username & backup repo
          git remote -v  # List remotes to verify

      - name: Pull changes from backup repository
        run: |
          echo "Pulling changes from backup repository"
          git pull backup feature-branch --rebase || echo "No changes to pull"  # EDIT: Pull from 'feature-branch' instead of 'main'

      - name: Check PAT permissions
        run: |
          echo "Checking PAT permissions"
          curl -H "Authorization: token ${{ secrets.PAT }}" https://api.github.com/user/repos

      - name: Push to backup repository
        run: |
          echo "Pushing to remote repository"
          git push backup ${{ env.BRANCH_NAME }} --force
