name: Backup Repository

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create a backup archive
        run: |
          zip -r backup_$(date +%F).zip . -x ".git/*"  # Creates a backup ZIP file, excluding .git directory

      - name: Prepare backup directory
        run: |
          mkdir -p backups  # Create backups directory if it doesn't exist

      - name: Move backup file to backups directory
        run: |
          mv backup_$(date +%F).zip backups/  # Move backup ZIP into the backups directory

      - name: Commit and push to backup branch
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          # Checkout the feature branch
          git checkout feature-branch  # Replace 'feature-branch' with your actual branch name

          # Pull the latest changes from the feature branch to make sure you're up to date
          git pull origin feature-branch

          # Create or switch to the backup-branch (create if it doesn't exist)
          git checkout -b backup-branch || git checkout backup-branch

          # Add the backup file to Git
          git add backups/

          # Commit the backup
          git commit -m "Automated backup on $(date)"

          # Push to the backup branch
          git push origin backup-branch
